[2024-05-22T22:06:01.930+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T22:06:01.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: disney_api.has_data manual__2024-05-22T22:05:58.927634+00:00 [queued]>
[2024-05-22T22:06:01.948+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: disney_api.has_data manual__2024-05-22T22:05:58.927634+00:00 [queued]>
[2024-05-22T22:06:01.949+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-22T22:06:01.962+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): has_data> on 2024-05-22 22:05:58.927634+00:00
[2024-05-22T22:06:01.969+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'disney_api', 'has_data', 'manual__2024-05-22T22:05:58.927634+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/disney_api_dag.py', '--cfg-path', '/tmp/tmptvq5fnyb']
[2024-05-22T22:06:01.972+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask has_data
[2024-05-22T22:06:01.973+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1088) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-22T22:06:01.973+0000] {standard_task_runner.py:63} INFO - Started process 1090 to run task
[2024-05-22T22:06:02.011+0000] {task_command.py:426} INFO - Running <TaskInstance: disney_api.has_data manual__2024-05-22T22:05:58.927634+00:00 [running]> on host 4f9488b8581a
[2024-05-22T22:06:02.079+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marcelo.vicente@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='disney_api' AIRFLOW_CTX_TASK_ID='has_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T22:05:58.927634+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T22:05:58.927634+00:00'
[2024-05-22T22:06:02.081+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T22:06:02.090+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-22T22:06:02.130+0000] {python.py:237} INFO - Done. Returned value was: saving_raw_data
[2024-05-22T22:06:02.131+0000] {branch.py:36} INFO - Branch into saving_raw_data
[2024-05-22T22:06:02.132+0000] {skipmixin.py:178} INFO - Following branch saving_raw_data
[2024-05-22T22:06:02.145+0000] {skipmixin.py:246} INFO - Skipping tasks [('alarm_dag', -1)]
[2024-05-22T22:06:02.164+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T22:06:02.185+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=disney_api, task_id=has_data, run_id=manual__2024-05-22T22:05:58.927634+00:00, execution_date=20240522T220558, start_date=20240522T220601, end_date=20240522T220602
[2024-05-22T22:06:02.229+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T22:06:02.257+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22T22:06:02.261+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
